# .github/workflows/deploy.yml
name: Deploy Demo to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🛠 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: 📦 Install Elm
        run: npm install -g elm

      - name: 🧱 Build Elm + prepare dist folder
        run: |
          mkdir dist
          cp index.html dist/index.html
          elm make src/Main.elm --output=dist/elm.js

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
